### ISSUE TITLE
possible optimization in _push_monomial()

### ISSUE THREAD

**Issue by cgogolin** [peterwittek/ncpol2sdpa#12]
If `apply_substitutions()` in `_push_monomial()` returns a polynomial (for which `monomial.is_Add` is true) instead of just a monomial then, when it recursively calls itself on each term it will again try to apply all the substitutions to each term. As this is a pretty costly operation and the generation of the SDP is really a bottleneck it would be better to avoid this, for example by adding an optional parameter `apply_substitions=true` to `_push_monomial()` with which applying substitutions can be suppressed.

**Comment by peterwittek** [comment]
This is a good point, it makes perfect sense.

**Comment by cgogolin** [comment]
Do you have a better proposal for how to implement this or shall I prepare a pull request with the solution outlined above?

**Comment by peterwittek** [comment]
I think the above proposal is perfect.
