### ISSUE TITLE
Warn about experimental code as default in apply_substitutions()

### ISSUE THREAD

**Issue by cgogolin** [peterwittek/ncpol2sdpa#13]
`apply_substitutions()` by default uses the experimental `fast_substitute()` method. Maybe it would be good to print a warning about this if `verbose>0` and offer a switch with which this behavior can be changed without the need to edit the library?

**Comment by peterwittek** [comment]
I can no longer come up with any possible case where the `fast_substitute()` method would fail. It works for all monomials of commuting and noncommuting variables, Hermitian or not. What would be better instead is to unit test all possible cases.

**Comment by peterwittek** [comment]
Commit 2e495af38155cbd2d672d913a3fd4c243dcb8af7 adds unit tests for `fast_substitute` and `apply_substitutions`.
