### ISSUE TITLE
Support repeated or alternating substitution in apply_substitutions()

### ISSUE THREAD

**Issue by cgogolin** [peterwittek/ncpol2sdpa#14]
`apply_substitutions()` doesn't seem to take into account situations in which repeated or alternating application of substitution rules could lead to a "simpler" form for a given monomial/polynomial.

**Comment by peterwittek** [comment]
Are you sure this is true? The loop inside this function keeps going over all substitutions as long as there is any change.

**Comment by cgogolin** [comment]
Sorry, this was just a misunderstanding.
