### ISSUE TITLE
Documentation of public fields in SdpRelaxation or implement getter methods

### ISSUE THREAD

**Issue by cgogolin** [peterwittek/ncpol2sdpa#16]
It would be nice if the public fields primal, dual, x_mat, y_mat of SdpRelaxation were documented in the online documentation. Alternatively one could make them private and expose public getter methods that could then also take the value of self.status into account and throw exceptions if the fields are accessed without the SDP being solved yet.

**Comment by peterwittek** [comment]
Commit 321ff367e2f81c342533a65a58f37bcb9d6e068c does this for the major public class attributes. It should be in the latest branch on RTD soon.

getters/setters are too Java-ish. I prefer to keep it simple. If a function is called that requires the SDP to be solved first, it will complain anyway.
