### ISSUE TITLE
Use multiprocessing to parallelize expensive operations

### ISSUE THREAD

**Issue by cgogolin** [peterwittek/ncpol2sdpa#24]

**Comment by peterwittek** [comment]
Parallelization leads to race conditions in the tests. Commit f51495b7770d888df7f411fc5ce8f32eece3fa97 sets default parallel execution to false.

**Comment by peterwittek** [comment]
Simplest example to reproduce the problem:

```
from ncpol2sdpa import generate_variables, SdpRelaxation
X = generate_variables('X', n_vars=1)[0]
sdpRelaxation = SdpRelaxation(X, parallel=True)
sdpRelaxation.get_relaxation(1, inequalities=[X + 0.5])
```

The floating point number is necessary in the constraint, otherwise it runs fine. The problem seems to be related to sympy/sympy#7457. It is not a race condition, but a weird pickling problem.

**Comment by peterwittek** [comment]
And as for pickling proper, the same problem surfaces

```
import pickle
from ncpol2sdpa import generate_variables, SdpRelaxation
X = generate_variables('X', n_vars=1)[0]
sdpRelaxation = SdpRelaxation(X, parallel=False)
sdpRelaxation.get_relaxation(1, inequalities=[X + 0.5])
filename = "test.pickle"
handle = open(filename, 'wb')
pickle.dump(sdpRelaxation, handle)
handle.close()
handle = open(filename, 'rb')
pickle.load(handle)
handle.close()
```

**Comment by peterwittek** [comment]
This is now complete with commits 1e700557f6a3889fbdaf025e090b1ca01b54a2d4 and 30f501b915ab921f2a7905c431e29438ce5e36eb. It will remain disabled by default until the patch for the sympy issue is accepted upstream.
