### ISSUE TITLE
NPA test for quantum correlations

### ISSUE THREAD

**Issue by dsuess** [peterwittek/ncpol2sdpa#35]
I am trying to implement a test using the NPA hierarchy to check whether a given set of correlations comes from a measurements on a quantum system. To check it, I have implemented different tests, one of which should fail (but doesn't). Please see the [Notebook](https://gist.github.com/anonymous/8945d9900b61a4e1b4d8c767d8691785) for details.

Is there sth wrong with the way I implement the test or do I have sth messed up with the way the NPA hierarchy works:
- the quasi-state that should fail is not positive-semidef.. The correlations are obtained from POVM measurements. Therefore, according to [this](https://arxiv.org/abs/0911.3606) paper, the correlations are non-signaling
- the NPA test checks compatibility with quantum measurements, which are rank-1 projections -- I generate the data from exactly these measurements. 
- even if there was another set of rank-1 POVMs, that generate the data, the corresponding state would still be not pos. semidef., since the eigenvalues are preserved under unitary transformations
- the generated expectation values are correct probabilities

**Comment by peterwittek** [comment]
I checked your code and the only tiny mistake is that you should pass the constraints as moment equalities:
```python
sdp.get_relaxation(level, momentequalities=constraints, substitutions=P.substitutions)
```
The NPA hierarchy only sees the correlations and it optimizes over all measurements and **all states**. As long as there is a PSD state which can reproduce the correlations, it will not report anything suspicious. In other words, it works in a device independent setting, not assuming anything about the state or measurements that produced the observed correlations.

**Comment by dsuess** [comment]
OK, thanks for the feedback. I thought you could make such an argument for a the first level of the hierarchy, but that seems to be a fallacy.

**Comment by peterwittek** [comment]
I wish we could. Then we could also fix the dimension of the states being optimized over...
